### ISSUE TITLE
Adventure's toolbox tools are uncraftable

### ISSUE THREAD

**Issue by Iplay2L8** [Kiyaku/SeriousEngineering#11]
version 1.0.5.3 seen Adventurer's tool parts in JEI.  They have no crafting recipe. checked config. schematics are turned off.  Recipe for replacing tool adornments are off.  and disable vanilla tools is off. Dont know if you intend to remove the mod or settings were changed in an update.

**Comment by SeriousCreeper** [comment]
check the changelog, they were disabled in the latest update cause some people's colonists had issue swith them. Use vanilla tools or tetra now :) I kept the mod in so that it wouldn't delete peoples tools if they were using them currently.
