### ISSUE TITLE
Question: Is common and rare gem spawning working as intended?

### ISSUE THREAD

**Issue by SuddenTurmoil** [Kiyaku/SeriousEngineering#13]
Playing 1.0.5.4. World started on 1.0.5.3. I got tired of the massive lag on world gen so when I upgraded to .5.4 I pregenerated 784,000 chunks. It took several days. I then went hunting for common and rare gems with a prospector pick, the geolysis manual, and notes written about the config file telling me what ores the techguns clusters spawn with. I traveled 6,000+ blocks in two directions and did not find a single instance of either. Eventually, I installed and configed Scannable to try to find them and that came up with nothing either. So, are they actually generating? I couldn't figure out how to make craftteaker actually tell me what biomes are tagged with what types so I may have been looking in the wrong spot but deserts, magical forests, savannas, ice plains, and ice spikes fit the bill for the descriptions of their spawn locations. I did find one spot in a desert that had a sample of assorted quartz and cinnabar (which I don't think is actually supposed to happen) but when right clicked they gave me nothing and there was no or vein under them. Checked with prospector pick, Scannable, and a good ol' manual search. I am probably going to cheat in the Techguns clusters at this point, and just put them somewhere reasonably far away from my base so I still have to make a train, but it has been a very disheartening journey (and my backup folder hates you now, 5GB world file says Hi).
Also, is there a better place / way to give general feedback or just a GitHub ticket with Suggestion: in it?
I don't mean to sound down on this pack. It's great and I love it. I have sunk...73 hours into it so far according to MultiMC.

**Comment by SeriousCreeper** [comment]
So you generated the chunks (that's a lot of chunks!) with .4 right? Cause in .3 there actually was a bug with those not spawning. I have found them myself in my world, but it is possible that they are a bit too uncommon or too small for enough samples to spawn on the surface. I'll see about increasing their size but reducing their density or something. 

Spawning in techguns ore blocks probably makes sense in your case. I actually had planned to add a merchant soon that sells a special item that lets you move the techguns ore blocks (but only place them adjacent of another techguns ore block of the same type, so you can't just put them into your base). 

Perhaps i could look into selling the ore blocks and have them only be placeable in their proper biomes. 

And no worries, i appreciate all the feedback, i wanna make sure you guys have a good experience with the pack too, and im happy to hear you are enjoying it so far! 
For bugs, github is still the best place, but if it's general feedback/questions, Discord is the best place to reach me (link to it is on the curseforge page)

**Comment by SuddenTurmoil** [comment]
The large generation was in .4, but I explored around my base a lot in .3 so I may have just been getting unlucky.  Being able to make bigger techguns clusters sounds cool, though with the storage and automation options present I don't think I really need to increase the output of them. I built a big factory out of lead sheetmetal and I haven't even built my rail system / started thaumcraft yet. 

Do you know what the proper biomes for the common and rare clusters to spawn in are? I would like to manually place them there but I couldn't figure out what biomes were associated with the tags hot, sandy, magical, jungle, cold, and snowy.

**Comment by SeriousCreeper** [comment]
1.6.0.1 has adjusted what biomes spawn what, and increased the chances slightly. Instead of showing biome types, it will show the exact biomes instead. Hope that helps!
