### ISSUE TITLE
Minecolony Farmers won't use Adventurer's Toolbox Hoes

### ISSUE THREAD

**Issue by dredgemage** [Kiyaku/SeriousEngineering#4]
Minecolony farmers won't work when given an Adventurer's Toolbox hoe. The same farmers do work when given a cheated in vanilla hoe.

Both hoes qualify for the request but when given the Adventurer's Toolbox hoe they deposit it in the farm's inventory.

**Comment by SeriousCreeper** [comment]
Did they use it once by chance, as in does the hoe have taken damage after they put it into the storage? I've noticed an issue with Minecolonies before where they see a fully repaired tool different from a broken one. Once i gave them the broken one back, they were fine with it (had to cancel the request for a tool as well)

**Comment by dredgemage** [comment]
Tested with both damaged and undamaged, same result either way.

**Comment by SeriousCreeper** [comment]
Hm dang, just tried too and yeah doesn't work, even with the wooden or stone one. I know for sure it worked in one of the previous versions while i was developing it. Reported it to minecolonies. 


What i might do in the mean time is to add a recipe to convert from a AT hoe (made out of the standard vanilla materials) into a vanilla hoe.

**Comment by SeriousCreeper** [comment]
added a recipe to make vanilla hoes using adventures toolbox hoes (in version 1.0.4). Temporary fix until minecolonies fixes that.
