### ISSUE TITLE
[suggestion] Link list to mod info (matching let'splay?)

### ISSUE THREAD

**Issue by NeddieSeagoon** [Kiyaku/SeriousEngineering#7]
Just an idea I had while playing the pack and watching the Let'splay:
Could be super handy to have all the links to the info pages of the mods in the pack collected in one area. 
Could maybe also be organized by Let'splay episode? ex:

I may just make a draft of this and submit a pull request if you're into it

**Comment by SeriousCreeper** [comment]
Did you have any more info on this? Still not quite sure what you mean
