### ISSUE TITLE
@Minecolonies

### ISSUE THREAD

**Issue by Valmora-Gaming** [Kiyaku/SeriousEngineering#8]
**Describe the bug**
Please mention the pack version, and include any crash logs if applicable
Because of other mods in this pack that change the mincraft nodes or removes them there are some building styles that can not be built, such as the "Stone Style" Blacksmith as it asks for 3 "vanilla" blocks of Iron, The other mod that makes the iron into the chunks when mined prevent this building from being able to be completed because its template asks for something that can not be given...
Plus the "Dwarven Style" asks for Vanilla minecraft wooden pick and sword, it will not accept the crafted ones, so you have to hunt for them in loot chests...

**Comment by Valmora-Gaming** [comment]
TAKEN FROM THE TWITCH TV info
Serious Engineering
By SeriousCreeper
Pack about long distance resource gathering and building a successful colony
Downloads: 188
Updated: 2/9/2020
Game Version: 1.12.2

**Comment by SeriousCreeper** [comment]
Did you close this cause it's not an issue after all? I'll double check this.
